/**
 * 阶段二离线测试：API-Key 注册表 + Bearer 校验 + 按账号共享闸门（风控核心）。
 *
 * 判据（AGENTS.md 2.4 都配反向验证）：
 *   - key → accountId 映射正确、key 原文不落盘（只活在进程内存 registry）
 *   - Bearer 提取/校验：缺 key / 错 key → 失败
 *   - 日志 maskKey：只留前 4 + ***，绝不全量暴露
 *   - **per-account 闸门**：两个请求绑同一账号必须走同一把 gate（串行），
 *     这是「同账号并发生成=最重风控触发」的防护。
 */
import assert from 'node:assert/strict'
import { buildKeyRegistry, maskKey } from '../server/api-key/keys.ts'
import { authenticate, bearerFromHeader } from '../server/http/auth.ts'
import { gateFor } from '../server/runtime.ts'

let passed = 0
const failures = []
async function run(name, fn) {
  try {
    await fn()
    passed += 1
  } catch (error) {
    failures.push(`x ${name}: ${error?.message ?? error}`)
  }
}

await run('env 映射：key@accId 正确拆分；逗号多个', async () => {
  process.env['DSW_API_KEYS'] = 'keyA@acc_111111,keyB@acc_222222'
  try {
    const { registry } = buildKeyRegistry('acc_current')
    assert.equal(registry.size, 2)
    assert.equal(registry.get('keyA')?.accountId, 'acc_111111')
    assert.equal(registry.get('keyB')?.accountId, 'acc_222222')
  } finally {
    delete process.env['DSW_API_KEYS']
  }
})

await run('未配置 env → 自动生成一个 key 绑当前账号', async () => {
  const { registry, autoGenerated } = buildKeyRegistry('acc_current')
  assert.ok(autoGenerated, '应自动生成一个 key')
  assert.equal(registry.size, 1)
  const key = autoGenerated
  assert.ok(key && registry.has(key), '生成的 key 应能查回')
  assert.equal(key && registry.get(key)?.accountId, 'acc_current')
})

await run('【反向】自动生成 key 有长度且唯一（不是固定硬编码）', async () => {
  const a = buildKeyRegistry('x')
  const b = buildKeyRegistry('x')
  delete process.env['DSW_API_KEYS']
  assert.ok(a.autoGenerated && b.autoGenerated, '两次都应自动生成')
  assert.notEqual(a.autoGenerated, b.autoGenerated, '随机 key 不能两次相同（否则客户端键可被猜）')
  assert.ok((a.autoGenerated ?? '').length >= 20, 'key 应有足够熵')
})

await run('maskKey：只留前 4 + ***，绝不全量', async () => {
  assert.equal(maskKey('dsw-abcdef123456'), 'dsw-***')
  assert.equal(maskKey(''), '')
  assert.ok(!maskKey('dsw-abdef123456').includes('def'), '掩码后不得包含完整中间段')
})

await run('Bearer 提取与校验：正确/缺/错', async () => {
  const { registry, autoGenerated } = buildKeyRegistry('acc_x')
  const key = autoGenerated
  const ok = authenticate(registry, `Bearer ${key}`)
  assert.equal(ok.ok, true, '正确 key 应通过')
  assert.equal(ok.ok && ok.entry.accountId, 'acc_x')
  assert.equal(authenticate(registry, undefined).ok, false, '无 Authorization → 失败')
  assert.equal(authenticate(registry, 'Bearer wrongkey').ok, false, '错 key → 失败')
})

await run('bearerFromHeader 容错大小写与空白', async () => {
  assert.equal(bearerFromHeader('Bearer abc'), 'abc')
  assert.equal(bearerFromHeader('bearer   abc  '), 'abc', '小写 + 多余空白')
  assert.equal(bearerFromHeader('Basic xxx'), undefined, '非 Bearer 方案 → undefined')
  assert.equal(bearerFromHeader(undefined), undefined)
})

// ── per-account 闸门共存（风控核心）───────────────────────────────────────
await run('同一账号多次 gateFor 返回同一把 gate；不同账号各一把', async () => {
  const g1 = gateFor('acc_a')
  const g2 = gateFor('acc_a')
  const g3 = gateFor('acc_b')
  assert.equal(g1, g2, '同一账号必须共享同一把锁（否则绕过防风控）')
  assert.notEqual(g1, g3, '不同账号各一把锁')
})

await run('【反向】闸门默认串行：同账号第二个 acquire 在第一个 release 前拿不到', async () => {
  const gate = gateFor('acc_serial')
  let entered = 0
  let maxConcurrent = 0
  const runTask = async () => {
    const release = await gate.acquire('test')
    entered += 1
    maxConcurrent = Math.max(maxConcurrent, entered)
    await new Promise((r) => setTimeout(r, 30))
    entered -= 1
    release()
  }
  await Promise.all([runTask(), runTask(), runTask()])
  assert.equal(maxConcurrent, 1, '默认必须串行（allowConcurrent=false），并发了就要红')
})

console.log()
console.log(`通过 ${passed} 项${failures.length ? `，失败 ${failures.length} 项` : '，全部通过 OK'}`)
for (const failure of failures) console.log('  ' + failure)
if (failures.length) process.exitCode = 1
