#!/usr/bin/env node
/**
 * dsh-deepseek-web-login —— 独立 OpenAI 兼容 API 服务入口。
 *
 * 把本机账号库的网页登录态包装成一个 OpenAI 兼容 HTTP 服务（不经 DSH 宿主）。
 * 风控优先：串行 + 随机间隔闸门、会话及时清理 + journal 补删、默认 Chromium 指纹传输、
 * 绝不自动换号、凭证绝不出 HTTP。
 *
 * 用法：
 *   node server/index.ts                    # 自动生成一个 key（首启打印一次）
 *   DSW_API_KEYS=mykey@acc_xxxx node server/index.ts
 *   DSW_PORT=8890 node server/index.ts      # 默认 127.0.0.1:8890
 *   DSW_TRANSPORT=node node server/index.ts # 强制走 Node 网络栈（默认 chromium）
 */
import { activeAccountId, listAccounts } from '../src/accounts.ts'
import { maskIdentifier } from '../src/auth.ts'
import { applyTransport } from '../src/transport.ts'
import { buildKeyRegistry } from './api-key/keys.ts'
import { runStartupSessionSweep } from './runtime.ts'
import { buildPoolManagers } from './pool/factory.ts'
import { startServer } from './http/server.ts'

function log(line: string): void {
  console.log(`[deepseek-web-api] ${line}`)
}

/** 读 `DSW_MAX_PROMPT_CHARS`（体量阀，夹在 src/gate.ts 的合法区间内），缺省 400_000。 */
function maxPromptCharsFromEnv(): number | undefined {
  const n = Number(process.env['DSW_MAX_PROMPT_CHARS'])
  if (!Number.isFinite(n) || n <= 0) return undefined
  return Math.min(1_500_000, Math.max(120_000, Math.round(n)))
}

/** 读 `DSW_LONG_RUN_THRESHOLD`（长任务休整阈值；0 = 关），缺省不覆盖（15）。 */
function longRunThresholdFromEnv(): number | undefined {
  const n = Number(process.env['DSW_LONG_RUN_THRESHOLD'])
  if (!Number.isFinite(n)) return undefined
  return Math.min(100, Math.max(0, Math.round(n)))
}

function main(): void {
  const accounts = listAccounts()
  if (accounts.length === 0) {
    log('⚠️  账号库为空 —— 请先在 DSH 里「DeepSeek 网页登录」添加账号，再启动本服务。')
    process.exit(1)
  }
  const currentAccount = activeAccountId()

  // 传输层：优先 Chromium 指纹（有系统浏览器走浏览器代理），否则安全降级 Node。
  // 独立服务用 DSW_TRANSPORT 显式控制（默认 chromium），不读 DSH 的 transport.json（保持独立）。
  const requested = process.env['DSW_TRANSPORT'] === 'node' ? 'node' : 'chromium'
  try {
    const state = applyTransport(requested)
    const detail =
      state.effective === 'chromium'
        ? state.viaBrowserProxy
          ? '浏览器代理（CDP，指纹真实）'
          : 'Chromium 网络栈'
        : state.degraded
          ? 'Node 网络栈（无可用浏览器/Chromium，安全降级）'
          : 'Node 网络栈'
    log(`传输层：${detail}`)
    if (state.effective === 'chromium' && !state.viaBrowserProxy && process.platform === 'win32') {
      // 纯 Node 下 Chromium 慢走系统代理（transport.ts 注释）；若失败可 --transport=node
      log('提示：若请求失败，可 DSW_TRANSPORT=node 强制走 Node 网络栈。')
    }
  } catch (error: any) {
    log(`传输层初始化失败（回退 Node）：${error?.message ?? error}`)
  }

  const { registry, autoGenerated } = buildKeyRegistry(currentAccount)

  if (autoGenerated) {
    log('未配置 DSW_API_KEYS，已自动生成一个 API Key（只在此打印一次，请妥善保存）：')
    log(`  ${autoGenerated}`)
    log(`  绑定账号：${maskIdentifier(accounts[0]?.user?.display) || '(当前账号)'}`)
  } else {
    log(`已加载 ${registry.size} 个 API Key（绑定账号均已在账号库）。`)
  }

  if (registry.size === 0) {
    log('没有可用键：请配置 DSW_ACCOUNT_ID 或用 DSW_API_KEYS=key@acc_xxxx。')
    process.exit(1)
  }

  // 启动补删上次遗留的会话（成功了才值得起服务）
  runStartupSessionSweep(true)

  const port = Number(process.env['DSW_PORT']) || 8890
  const server = startServer(
    {
      registry,
      deleteWebSessions: true,
      log,
      // 账号池：为带 poolScope 的 key 装配 PoolManager（池选号 + failover）。
      poolManagers: buildPoolManagers(registry, { log }),
      // 风控体量阀 + 长任务休整（缺省即安全默认，见 src/gate.ts 同源常量）。
      maxPromptChars: maxPromptCharsFromEnv(),
      longRunThreshold: longRunThresholdFromEnv(),
    },
    port,
  )

  server.on('error', (error: any) => {
    log(`启动失败：${error?.message ?? error}`)
    process.exit(1)
  })
}

main()
