/**
 * API-Key → accountId / 池 映射（阶段二：一个 key 绑一个账号；改造后支持绑账号池）。
 *
 * 来源优先级：
 *   ① 环境变量 `DSW_API_KEYS=key1@acc_xxx,key2@acc_xxx,key3@pool[-scope]`（多个用逗号分隔）
 *       - `@acc_xxx`          ⇒ 单账号直通（默认，与以前完全一致）。
 *       - `@pool`             ⇒ 绑账号池；具体 scope 由 DSW_POOL_SCOPE 决定（缺省关）。
 *       - `@pool-roundrobin`  ⇒ 均衡轮换（默认关，见 server/pool/pool.ts）。
 *       - `@pool-failover`    ⇒ 失效换号（默认关）。
 *   ② 未设置 ⇒ 自动生成一个随机 key 绑到「当前账号」，启动时打印一次（含完整 key，只在首启打印）。
 *
 * ⚠️ 安全底线（AGENTS.md 2.5）：key 的**原始值**绝不落盘、绝不打进日志/HTTP 响应；
 * 这里只维护「原文 → accountId/池」的**进程内映射**（key 本身留在进程内存，天然不持久化）。
 * 日志只打掩码（前 4 + ***）。
 */
import { randomBytes } from 'node:crypto'
import { maskIdentifier } from '../../src/auth.ts'
import {
  POOL_SCOPE_ENV,
  normalizePoolScope,
  parsePoolBinding,
  type PoolScope,
} from '../pool/pool.ts'

export interface KeyEntry {
  /** API-Key 原文（只活在进程内存）。 */
  key: string
  /** 绑定账号（单账号直通 = 唯一账号；池 = 首选/当前账号锚点，per-request 由池选号决定）。 */
  accountId: string
  /** 池作用域。undefined = 单账号直通（默认）。 */
  poolScope?: PoolScope
  /** 展示用短名（掩码）。 */
  label: string
}

export type KeyRegistry = Map<string, KeyEntry> // key原文 -> entry

const KEY_ENV = 'DSW_API_KEYS'
const DEFAULT_ACCOUNT_ID_ENV = 'DSW_ACCOUNT_ID'

/** 掩码展示 key：只留前 4 位 + ***。 */
export function maskKey(key: string): string {
  if (!key) return ''
  return `${key.slice(0, 4)}***`
}

function parseEnvValue(raw: string, currentAccountId: string | undefined): KeyEntry[] {
  const out: KeyEntry[] = []
  const envPoolScope = normalizePoolScope(process.env[POOL_SCOPE_ENV])
  for (const part of raw.split(',')) {
    const piece = part.trim()
    if (!piece) continue
    const at = piece.lastIndexOf('@')
    if (at <= 0 || at === piece.length - 1) {
      // 没有显式绑定 → 单账号直通，绑当前账号（若拿不到则跳过并提示）
      if (currentAccountId) out.push({ key: piece, accountId: currentAccountId, label: maskKey(piece) })
      continue
    }
    const key = piece.slice(0, at)
    const { accountId, poolScope } = parsePoolBinding(piece.slice(at + 1), envPoolScope)
    // 池的 accountId 是"首选锚点"（可选，可为空 —— 选号时从账号库现取）；
    // 单账号直通（无 poolScope）则必须是实际账号 id（拿不到当前账号时留空，等真正解析时再判）。
    out.push({ key, accountId: accountId || currentAccountId || '', poolScope, label: maskKey(key) })
  }
  return out
}

/**
 * 构建 key 注册表。
 * @param currentAccountId 当前账号 id（env 未显式绑定时兜底；无当前账号时返回空表）
 * @returns { registry, autoGenerated } autoGenerated 为 true 时表示自动生成了一个 key，
 *           完整 key 只在本函数返回后在**首次启动日志**里打印一次。
 */
export function buildKeyRegistry(
  currentAccountId: string | undefined,
): { registry: KeyRegistry; autoGenerated: string | undefined } {
  const registry: KeyRegistry = new Map()

  const envRaw = process.env[KEY_ENV]
  if (envRaw && envRaw.trim()) {
    for (const entry of parseEnvValue(envRaw, currentAccountId)) {
      if (entry.key && registry.has(entry.key)) continue
      registry.set(entry.key, entry)
    }
    if (registry.size > 0) return { registry, autoGenerated: undefined }
  }

  // 未配置 → 自动生成一个绑当前账号
  const accountId = process.env[DEFAULT_ACCOUNT_ID_ENV] || currentAccountId
  if (!accountId) return { registry, autoGenerated: undefined }
  const key = `dsw-${randomBytes(18).toString('base64url')}`
  registry.set(key, { key, accountId, label: maskKey(key) })
  return { registry, autoGenerated: key }
}

export { DEFAULT_ACCOUNT_ID_ENV, maskIdentifier }
